### ISSUE TITLE
systemd-journal-logger v2.0.0 requires memfd_create in libc

### ISSUE THREAD

**Issue by daniestevez** [swsnr/systemd-journal-logger.rs#22]
I am trying to update an embedded application to systemd-journal-logger v2.0.0, but I am facing the issue that the system where this runs doesn't have `memfd_create()` in libc (it has glibc 2.23, and `memfd_create()` was added in glibc 2.27). I already found this problem in the libsystemd-rs crate, and it was solved in with https://github.com/lucab/libsystemd-rs/pull/144.

It seems that the nix crate has a PR that will use the syscall instead of the libc function when compiling for glibc in order to account for old glibc versions: https://github.com/nix-rust/nix/pull/2146

What are your thoughts on the implications of this for systemd-journal-logger? A possible solution is to call `nix::memfd_create` instead of `libc::memfd_create` after the nix PR makes it into a release. However that brings in nix as an additional dependency. Another option is to replace the call to `libc::memfd_create` with the syscall, which is what we already did in libsystemd-rs.

**Comment by swsnr** [comment]
My stance on supporting a glibc that old hasn't changed.

You'll need to keep using an older version of this crate or carry your own patches.

**Comment by daniestevez** [comment]
If I could update the glibc in this system I would, but this is outside of my control. So unfortunately "carry your own patches" it is.

**Comment by swsnr** [comment]
Sorry accidentally pressed the wrong button

**Comment by swsnr** [comment]
Coincidentally fixed by #24
