### ISSUE TITLE
Per Module Log Levels?

### ISSUE THREAD

**Issue by codifryed** [swsnr/systemd-journal-logger.rs#25]
Hi there, I have several chatty modules (dependencies) and I would like to be able to control their log levels individually, like one does in env_logger.

Is there a way to do this that perhaps I'm not aware of?

**Comment by swsnr** [comment]
Not in this crate, but you write your own log implementation on top of this logger, and then use the filter functionality of env_logger, or apply your own custom filtering logic.

**Comment by swsnr** [comment]
See https://github.com/swsnr/logcontrol.rs/blob/f52d748de7dc3cb5c9317432999865db539f0718/log-reload/src/lib.rs#L27 for a simple generic log wrapper with basic level filtering.

**Comment by codifryed** [comment]
Thanks @swsnr. 
I really like this crate, just wanting to do some tweaking. 😄 I also wasn't sure if it's something that would want to be a part of this crate or not, (willing to make a PR) but I'm happy to add on top of this if that's the way to go.

**Comment by swsnr** [comment]
It's out of scope for this extension.  It's trivial to add your own filtering logic on top of this logger 🙂
